# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fugazzi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(unique=True)),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedate', fugazzi.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('broken', models.NullBooleanField()),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedate', fugazzi.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('image', models.CharField(max_length=100)),
                ('language', models.CharField(default=b'English', max_length=100)),
                ('summary', models.TextField()),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedate', fugazzi.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedate', fugazzi.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('movies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(default=1, unique=True)),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedate', fugazzi.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('image', models.TextField()),
                ('language', models.TextField(default=b'English', max_length=100, null=True)),
                ('summary', models.TextField()),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedate', fugazzi.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedate', fugazzi.models.AutoDateTimeField(default=django.utils.timezone.now, editable=False)),
                ('movies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Movies')),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Series')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Series'),
        ),
        migrations.AddField(
            model_name='popular',
            name='series',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Series'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Links'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Season'),
        ),
    ]
