# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-11 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('viewlink', models.CharField(max_length=100)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('quality', models.CharField(max_length=20)),
                ('downloadable', models.BooleanField()),
                ('broken', models.NullBooleanField()),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.CharField(max_length=100)),
                ('viewlink', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('releaseyear', models.IntegerField()),
                ('summary', models.TextField()),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('links', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Links')),
            ],
        ),
        migrations.CreateModel(
            name='Popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('movies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Movies')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('numofepisodes', models.IntegerField()),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('episodes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Episodes')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.TextField()),
                ('viewlink', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('numofseasons', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('movies', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Movies')),
                ('series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Series')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Series'),
        ),
        migrations.AddField(
            model_name='popular',
            name='series',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Series'),
        ),
        migrations.AddField(
            model_name='episodes',
            name='links',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Links'),
        ),
        migrations.AddField(
            model_name='cast',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Movies'),
        ),
    ]
