# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fugazzi', '0002_auto_20170120_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
