# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fugazzi', '0003_auto_20170121_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='episodes',
        ),
        migrations.RemoveField(
            model_name='season',
            name='season_no',
        ),
        migrations.AddField(
            model_name='episodes',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Season'),
        ),
        migrations.AddField(
            model_name='season',
            name='title',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='title',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='language',
            field=models.CharField(default=b'English', max_length=100),
        ),
    ]
