# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fugazzi', '0004_auto_20170122_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fugazzi.Season'),
        ),
    ]
