# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fugazzi', '0005_auto_20170122_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(default=b'English', max_length=100),
        ),
    ]
